# Generated by Django 3.0.3 on 2020-02-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.TextField(max_length=264)),
                ('trade_name', models.TextField(max_length=264)),
                ('alternate1', models.TextField(max_length=264)),
                ('alternate2', models.TextField(max_length=264)),
                ('qnt', models.PositiveIntegerField()),
                ('item_price', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_qnt', models.PositiveIntegerField()),
                ('sell_price', models.PositiveIntegerField()),
                ('sell_date', models.DateTimeField()),
                ('med_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharma.Medicine')),
            ],
        ),
    ]
