# Generated by Django 3.0.3 on 2020-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='qnt',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
