# Generated by Django 3.0.3 on 2020-02-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharma', '0002_auto_20200204_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='alternate1',
            field=models.TextField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='alternate2',
            field=models.TextField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='item_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='scientific_name',
            field=models.TextField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='trade_name',
            field=models.TextField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='sell_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='sell_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='sell_qnt',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
